### ISSUE TITLE
Toggle Link and Unlink

### ISSUE THREAD

**Issue by gayanhewa** [colinmollenhour/modman#36]
@colinmollenhour 

Great way to manage my Magento code ! :100:  I just couldn't find how to use modeman to link and unlink the modules.

I mean like install and remove them using modman :)

Thanks,

@gayanhewa

**Comment by pocallaghan** [comment]
I've modified my local modman to add "undeploy", I went with undeploy rather than unlink since it's the spiritual opposite of deploy (you don't specify a src path, it basically just parses the modman file of a module in your .modman directory). I find this extremely useful in my workflow. Whilst it's true that deploy-all would re-deploy the module, my workflow doesn't really including using deploy-all so this isn't an issue for me (we deploy modules individually and commit the symlinks).

I used a bit of a hacky approach because I don't know a great deal about bash scripting:

```
  undeploy)
    require_wc "$module" || exit 1
    wc_dir_tmp="$wc_dir"-tmp
    mv "$wc_dir" "$wc_dir_tmp" && remove_dead_links && echo "$module has been unlinked" && mv "$wc_dir_tmp" "$wc_dir"
    ;;
```

I'd be happy to update to the latest version (I forked awhile ago) and make a pull request, however I wasn't sure how likely it was to be accepted.

**Comment by colinmollenhour** [comment]
@pocallaghan that is certainly a valid way to do it but not really ideal since for example the IDE could have files open that are being moved. However, the "proper" way to do it is slower and more difficult but would probably be something like:

1. Use find to get all symlinks
2. Use readlink to narrow down to the ones that are in the module
3. Delete the links

To keep the module from being redeployed perhaps a flag file could be placed in the root (.modman-skip).

**Comment by pocallaghan** [comment]
Any insights as to how to get around the fact that readlink doesn't support the -f flag on mac/bsd based systems, so getting the absolute path of the symlink target seems non-trivial?

**Comment by pocallaghan** [comment]
As the undeploy command was merged, I believe this issue can now be closed?

**Comment by colinmollenhour** [comment]
Yes. Thanks.
