### ISSUE TITLE
.gitmodules is not created / updated

### ISSUE THREAD

**Issue by nocturnalfrog** [colinmollenhour/modman#44]
Modman does not create an entry in the _.gitmodules_ file when installing a module. 
As a result you can no longer update other git submodules in the parent repo.

When executing the _git submodule update_ command:
`> git submodule update --init --recursive`
You get the following error:
`No submodule mapping found in .gitmodules for path '.modman/Cm_Cache_Backend_Redis'`

When installing the _Cm_Cache_Backend_Redis_ module:
`> modman clone git://github.com/colinmollenhour/Cm_Cache_Backend_Redis.git`

I would expect to find the following entry in the _.gitmodules_ file of the parent repo:

```
[submodule "Cm_Cache_Backend_Redis"]
path = .modman/Cm_Cache_Backend_Redis
url = git://github.com/colinmollenhour/Cm_Cache_Backend_Redis.git
```

I have added these lines manually for now but I am not sure if this will cause problems further down the track.

**Comment by jlaustill** [comment]
+1, I'd give it +1,000,000 if I could.  I just wasted SOOOOOOOO much time because of this not realizing that modman was creating submodules but not.  I've never used submodules before, so this confused the HECK out of me.  I've been cloning on my qa and prod servers manually because I couldn't for the life of me figure out why my modman installs won't commit properly.  

This might not seem like complexity worth adding to you, but it sure is for people like me that are new to the entire ecosystem... :)

**Comment by colinmollenhour** [comment]
Modman manages repos at the module-level, it does not manage .modman as a repo itself. You can do it, but it is not how modman's VCS features were designed to be used. I'm sorry for the confusion and would be happy to accept documentation improvements.

FWIW, here is a simplified way I use modman:

```
cd /some/path
modman init
git clone <path_to_magento_core_repo> htdocs
modman clone --basedir magento-root <path_to_some_repo>
modman clone --basedir magento-root <path_to_some_repo>
...
```

Now given the above *if* you wanted to manage each modman module as a submodule you could do:

```
cd /some/path
git init
git submodule add htdocs
git submodule add .modman/module1
git submodule add .modman/module2
git commit -a -m "Added root and modman modules"
git remote add origin <some_remote>
git push -u origin master
```

And then to clone the entire thing to a new location:

```
cd /some/path
git clone <some_remote> root
cd root
git submodule update --init
modman deploy-all
```

Then your web root would be at /some/path/root/htdocs and your .modman directory would be *above* that path which is an improvement security-wise.

To pull in submodule updates:

```
cd /some/path
git pull
git submodule update --init
modman deploy-all
```

There are many ways to do it, the above is just one of them but is proof of concept if you want to manage modules as git submodules.

**Comment by jlaustill** [comment]
Ok, bear with me because as I said, never used submodules before.  What I'm not grasping is how you expect this to work if you DON'T treat them as submodules?

Take a step back for a moment and forget modman.  If you just clone another repo inside your repo, like this 
git clone https://gist.github.com/glaucia86/000193ad507c8229cff69c03d7b2eb57
cd 000193ad507c8229cff69c03d7b2eb57/
git clone https://gist.github.com/d447b3bbc24d5014599e9d94ffc1fa1f.git

You create a broken submodule, because git see's the .git directory from repo2 and treats it as such.  When you do git status, you get 
`On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	d447b3bbc24d5014599e9d94ffc1fa1f/`

If you add and commit that, git treats it like a file but it will NOT allow you to commit what's inside that repo and rightly so. Then go into the sub repo and change a file, you get 

`On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   d447b3bbc24d5014599e9d94ffc1fa1f (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")`

If you then add this and commit, push and pull to a new server, git will NOT sync that sub module, it will just create an empty directory.  If you try to git pull inside that directory, git fails because it didn't track it as a sub module.  The entire thing is just broken and wrong so far as I can see. 

This is what I've been dealing with after installing with modman on my dev box and moving to my qa and prod servers.  So I've been manually adding a remote to each empty directory and setting origin master and pulling.  I've also just deleted the directory and recloned because I can't install modman on my servers.

After manually creating a .gitmodules and pushing and pulling, git will sync the submodules commits from my dev box to my qa box.  So, what am I missing?  This just seems like a broken workflow to me without modman adding the submodule reference?

I'm fully aware that I could be wrong and I just am missing the obvious?

**Comment by pocallaghan** [comment]
I'm not sure what platform you're running on (i.e. OS / git version) but a couple of your assertions are certainly not true in all environments. Specifically `You create a broken submodule, because git see's the .git directory from repo2 and treats it as such.` and `If you add and commit that, git treats it like a file but it will NOT allow you to commit what's inside that repo and rightly so.`. 

If you completely ignore the fact that git has a concept of a submodule, it is entirely possible to clone a repo inside another repo and track the files in both repos. At the bottom of this post is a copy of the terminal output from a quick test, which is hopefully fairly self-explanatory, but basically, I create a basic repo, I create another repo in a child directory commit the file in the child repo, return to the parent and also commit the file. I then clone the parent repo to prove I still have all files from the child repo in the clone. What you don't have is the child repo itself (i.e. it's .git folder and independent history), only its files.

From my experience, if you're just trying to maintain your site this doesn't matter too much. If you need to update that module on a separate clone (say a second developer that cloned the site), they can delete the contents of the 'submodule' folder and clone it down again. Admittedly that's a manual step, but at my company, the next logical step to this was to use composer to pull in the repo and modman to deploy it. Don't have the files in your main repo at all.

```
mbp:~ pocallaghan$ cd /tmp/
mbp:tmp pocallaghan$ mkdir repo
mbp:tmp pocallaghan$ cd repo/
mbp:repo pocallaghan$ touch foo.txt
mbp:repo pocallaghan$ git init
Initialized empty Git repository in /private/tmp/repo/.git/
mbp:repo pocallaghan$ git add .
mbp:repo pocallaghan$ git commit -m "Start repo"
[master (root-commit) e47f912] Start repo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo.txt
mbp:repo pocallaghan$ mkdir sub-module
mbp:repo pocallaghan$ cd sub-module/
mbp:sub-module pocallaghan$ touch submodule_file.txt
mbp:sub-module pocallaghan$ git init
Initialized empty Git repository in /private/tmp/repo/sub-module/.git/
mbp:sub-module pocallaghan$ git add .
mbp:sub-module pocallaghan$ git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   submodule_file.txt

mbp:sub-module pocallaghan$ git commit -m "Start 'submodule'"
[master (root-commit) 908b00b] Start 'submodule'
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 submodule_file.txt
mbp:sub-module pocallaghan$ cd ../
mbp:repo pocallaghan$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	sub-module/

nothing added to commit but untracked files present (use "git add" to track)
mbp:repo pocallaghan$ git add sub-module/
mbp:repo pocallaghan$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   sub-module/submodule_file.txt

mbp:repo pocallaghan$ git commit -m "Adding files from submodule to main repo, not a submodule."
[master d1f7b26] Adding files from submodule to main repo, not a submodule.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 sub-module/submodule_file.txt
mbp:repo pocallaghan$ git status
On branch master
nothing to commit, working tree clean
mbp:repo pocallaghan$ cat .git/
COMMIT_EDITMSG  HEAD            config          description     hooks/          index           info/           logs/           objects/        refs/
mbp:repo pocallaghan$ cd sub-module/
mbp:sub-module pocallaghan$ touch new-submodule-file.txt
mbp:sub-module pocallaghan$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	new-submodule-file.txt

nothing added to commit but untracked files present (use "git add" to track)
mbp:sub-module pocallaghan$ cd ../
mbp:repo pocallaghan$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	sub-module/new-submodule-file.txt

nothing added to commit but untracked files present (use "git add" to track)
mbp:repo pocallaghan$ git add sub-module/new-submodule-file.txt
mbp:repo pocallaghan$ git commit -m "Added to main repo, not in 'submodule'."
[master 01b2920] Added to main repo, not in 'submodule'.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 sub-module/new-submodule-file.txt
mbp:repo pocallaghan$ cd sub-module/
mbp:sub-module pocallaghan$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	new-submodule-file.txt

nothing added to commit but untracked files present (use "git add" to track)
mbp:sub-module pocallaghan$ mkdir /tmp/repo2
mbp:sub-module pocallaghan$ cd /tmp/repo
mbp:repo pocallaghan$ cd /tmp/repo2
mbp:repo2 pocallaghan$ git clone /tmp/repo
Cloning into 'repo'...
done.
mbp:repo2 pocallaghan$ ls -la repo/
.git/       foo.txt     sub-module/ 
mbp:repo2 pocallaghan$ ls -la repo/
.git/       foo.txt     sub-module/ 
mbp:repo2 pocallaghan$ ls -la repo/sub-module/
total 0
drwxr-xr-x  4 pocallaghan  wheel  136  1 Mar 19:25 .
drwxr-xr-x  5 pocallaghan  wheel  170  1 Mar 19:25 ..
-rw-r--r--  1 pocallaghan  wheel    0  1 Mar 19:25 new-submodule-file.txt
-rw-r--r--  1 pocallaghan  wheel    0  1 Mar 19:25 submodule_file.txt
mbp:repo2 pocallaghan$ git --version
git version 2.11.1
```

**Comment by jlaustill** [comment]
That's a valid point; environment may very well be important here.  I see you are on a mac, I'm on Ubuntu 16.04 and my behavior seems to match yours when typing these exact commands.  My git version is 2.7.4.  So what is modman doing differently that doesn't allow me to add the files inside each sub repo?

That being said, I'm not sure what the behavior is "supposed" to be either.  I have never cloned a repo inside another repo before.  I've always used a package manager like npm, bower, or nu-get and versioned my files.

One thing I do know is that I CAN'T manage my repo like you do.  I can not install modman on my qa or prod servers.  And I can not expect my other developers to understand how to clone their own copies.  I need to use submodules so git can sync them.  I'm 100% open to learning new things and discussion on this however.

**Comment by colinmollenhour** [comment]
If you can't run modman in your deployment environment then you just need to add and commit the symlinks somewhere but I think everything else I suggested still holds. The symlinks will be broken unless the submodules are cloned.

Briefly regarding how to use submodules: you don't "git add" the submodule files, you only "git submodule add" the root of the submodule repo and git adds this to it's .gitmodules file and you commit this file.
